-- Catálogo maestro del restaurante. Generado; no editar manualmente.
insert into public.products (id, workspace_id, code, official_name, category, default_unit, allowed_units, synonyms, active)
values
  ('prod-aba-103', 'main', 'ABA-103', 'Aceite de oliva extra virgen', 'Abarrotes', 'garrafa', array['garrafa', 'L']::text[], array['ACEITE DE OLIVA EXTRAVIRGEN GALON', 'Aceites de oliva extra virgen', 'ACEITE OLIVA EXTRA VIRGEN 1/5 Litros']::text[], true),
  ('prod-aba-250', 'main', 'ABA-250', 'Aceite de Sesamo Lata', 'Abarrotes', 'lata', array['lata']::text[], array['Aceites de Sesamo Lata']::text[], true),
  ('prod-aba-109', 'main', 'ABA-109', 'Aceite en Aerosol', 'Abarrotes', 'und', array['und']::text[], array['Aceites en Aerosol']::text[], true),
  ('prod-aba-110', 'main', 'ABA-110', 'Aceite para Freidora 17l', 'Abarrotes', 'L', array['L']::text[], array['Aceite para Freidora', 'Aceites para Freidora']::text[], true),
  ('prod-aba-104', 'main', 'ABA-104', 'Aceite Soya Clover (pichinga)', 'Abarrotes', 'pichinga', array['pichinga']::text[], array['Aceite Soya Clover', 'Aceites Soya Clover']::text[], true),
  ('prod-aba-105', 'main', 'ABA-105', 'Aceituna Negra', 'Abarrotes', 'lata', array['lata']::text[], array['Aceitunas Negra']::text[], true),
  ('prod-aba-248', 'main', 'ABA-248', 'Aceituna Verde con Pimiento 2,0', 'Abarrotes', 'paquete', array['paquete', 'g']::text[], array['Aceitunas Verde con Pimiento 2,0']::text[], true),
  ('prod-aba-247', 'main', 'ABA-247', 'Achiote Taza 1', 'Abarrotes', 'und', array['und']::text[], array['Achiotes Taza 1']::text[], true),
  ('prod-aba-106', 'main', 'ABA-106', 'Aderezo Ranchero 2,0', 'Abarrotes', 'paquete', array['paquete']::text[], array['Aderezos Ranchero 2,0']::text[], true),
  ('prod-aba-246', 'main', 'ABA-246', 'Agua Tapa Rosca 600 Ml', 'Abarrotes', 'und', array['und']::text[], array['Agua Tapa Rosca', 'Aguas Tapa Rosca']::text[], true),
  ('prod-aba-245', 'main', 'ABA-245', 'Ajonjoli Negro', 'Abarrotes', 'kg', array['kg']::text[], array['Ajonjolis Negro']::text[], true),
  ('prod-aba-139', 'main', 'ABA-139', 'Alcaparras', 'Abarrotes', 'und', array['und']::text[], array[]::text[], true),
  ('prod-aba-264', 'main', 'ABA-264', 'Alfajores', 'Abarrotes', 'und', array['und']::text[], array[]::text[], true),
  ('prod-aba-244', 'main', 'ABA-244', 'Alga Nori', 'Abarrotes', 'paquete', array['paquete']::text[], array['Algas Nori']::text[], true),
  ('prod-aba-243', 'main', 'ABA-243', 'Almendra Rebanada', 'Abarrotes', 'kg', array['kg']::text[], array['Almendras Rebanada']::text[], true),
  ('prod-aba-120', 'main', 'ABA-120', 'Arrollado de Jamón', 'Abarrotes', 'und', array['und']::text[], array['Arrollados de Jamón']::text[], true),
  ('prod-aba-003', 'main', 'ABA-003', 'Arroz', 'Abarrotes', 'paquete', array['paquete', 'kg', 'g', 'bolsa']::text[], array['arroces', 'paquete de arroz', 'paquetes de arroz']::text[], true),
  ('prod-aba-125', 'main', 'ABA-125', 'Arroz 91% 12/1.8kg', 'Abarrotes', 'paquete', array['paquete']::text[], array['Arroz 91% 12/', 'Arroces 91% 12/']::text[], true),
  ('prod-aba-242', 'main', 'ABA-242', 'Arroz para Sushi', 'Abarrotes', 'kg', array['kg']::text[], array['Arroces para Sushi']::text[], true),
  ('prod-aba-241', 'main', 'ABA-241', 'Arroz Risotto', 'Abarrotes', 'paquete', array['paquete', 'g']::text[], array['Arroces Risotto']::text[], true),
  ('prod-aba-138', 'main', 'ABA-138', 'Atún en Bolsa', 'Abarrotes', 'und', array['und']::text[], array['Atunes en Bolsa']::text[], true),
  ('prod-aba-133', 'main', 'ABA-133', 'Avena', 'Abarrotes', 'envase', array['envase', 'kg']::text[], array['Avenas']::text[], true),
  ('prod-aba-002', 'main', 'ABA-002', 'Azúcar', 'Abarrotes', 'kg', array['kg', 'g', 'bolsa', 'paquete']::text[], array['azucar', 'azúcares', 'azucares']::text[], true),
  ('prod-aba-240', 'main', 'ABA-240', 'Azucar Blanco Doña Maria 12/2kg', 'Abarrotes', 'bulto', array['bulto']::text[], array['Azucar Blanco Doña Maria 12/', 'Azucares Blanco Doña Maria 12/']::text[], true),
  ('prod-aba-239', 'main', 'ABA-239', 'Azucar Indiviadual en Sobres Corriente', 'Abarrotes', 'empaque', array['empaque']::text[], array['Azucares Indiviadual en Sobres Corriente']::text[], true),
  ('prod-aba-238', 'main', 'ABA-238', 'Azucar Molido', 'Abarrotes', 'paquete', array['paquete']::text[], array['Azucares Molido']::text[], true),
  ('prod-aba-237', 'main', 'ABA-237', 'Azucar Moreno D. Maria 500 Grs', 'Abarrotes', 'und', array['und']::text[], array['Azucar Moreno D. Maria', 'Azucares Moreno D. Maria']::text[], true),
  ('prod-aba-236', 'main', 'ABA-236', 'Azucar Moreno Individual Sobres', 'Abarrotes', 'empaque', array['empaque']::text[], array['Azucares Moreno Individual Sobres']::text[], true),
  ('prod-aba-235', 'main', 'ABA-235', 'Azucar Splenda Dietitica', 'Abarrotes', 'caja', array['caja']::text[], array['Azucares Splenda Dietitica']::text[], true),
  ('prod-aba-234', 'main', 'ABA-234', 'Bebida Inst Cas Mfs 1/1800gr', 'Abarrotes', 'und', array['und']::text[], array['Bebida Inst Cas Mfs 1/', 'Bebidas Inst Cas Mfs 1/']::text[], true),
  ('prod-aba-233', 'main', 'ABA-233', 'Bebida Inst Frutas Mfs 1/1800gr', 'Abarrotes', 'und', array['und']::text[], array['Bebida Inst Frutas Mfs 1/', 'Bebidas Inst Frutas Mfs 1/']::text[], true),
  ('prod-aba-232', 'main', 'ABA-232', 'Bebida Inst Guanabana Mfs 1/1800gr', 'Abarrotes', 'und', array['und']::text[], array['Bebida Inst Guanabana Mfs 1/', 'Bebidas Inst Guanabana Mfs 1/']::text[], true),
  ('prod-aba-231', 'main', 'ABA-231', 'Bebida Inst Limonada Hierba Buena Mfs 1/1800gr Mayca', 'Abarrotes', 'und', array['und']::text[], array['Bebida Inst Limonada Hierba Buena Mfs 1/', 'Bebidas Inst Limonada Hierba Buena Mfs 1/']::text[], true),
  ('prod-aba-230', 'main', 'ABA-230', 'Bebida Inst Naranja Mfs 1/1800gr', 'Abarrotes', 'und', array['und']::text[], array['Bebida Inst Naranja Mfs 1/', 'Bebidas Inst Naranja Mfs 1/']::text[], true),
  ('prod-aba-229', 'main', 'ABA-229', 'Bebida Instantanea Te Melocoton Mfs 1800 Grs Mayca', 'Abarrotes', 'und', array['und']::text[], array['Bebida Instantanea Te Melocoton Mfs', 'Bebidas Instantanea Te Melocoton Mfs']::text[], true),
  ('prod-aba-228', 'main', 'ABA-228', 'Bicarbonato', 'Abarrotes', 'paquete', array['paquete']::text[], array['Bicarbotano', 'Bicarbonatos']::text[], true),
  ('prod-aba-225', 'main', 'ABA-225', 'Bocadillo C/ Crema Pastelera', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos C/ Crema Pastelera']::text[], true),
  ('prod-aba-227', 'main', 'ABA-227', 'Bocadillo con Carne Molida', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos con Carne Molida']::text[], true),
  ('prod-aba-223', 'main', 'ABA-223', 'Bocadillo Costilla C/ Fresa', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos Costilla C/ Fresa']::text[], true),
  ('prod-aba-121', 'main', 'ABA-121', 'Bocadillo Costilla C/ Mora', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos Costilla C/ Mora']::text[], true),
  ('prod-aba-224', 'main', 'ABA-224', 'Bocadillo Costilla C/ Piña', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos Costilla C/ Piña']::text[], true),
  ('prod-aba-220', 'main', 'ABA-220', 'Bocadillo Costilla de Guayaba', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos Costilla de Guayaba']::text[], true),
  ('prod-aba-252', 'main', 'ABA-252', 'Bocadillo de Fresa', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos de Fresa']::text[], true),
  ('prod-aba-131', 'main', 'ABA-131', 'Bocadillo de Guayaba.', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos de Guayaba.']::text[], true),
  ('prod-aba-222', 'main', 'ABA-222', 'Bocadillo de Jamón y Queso', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos de Jamón y Queso']::text[], true),
  ('prod-aba-122', 'main', 'ABA-122', 'Bocadillo de palmito', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos de palmito']::text[], true),
  ('prod-aba-123', 'main', 'ABA-123', 'Bocadillo de papa y carne', 'Abarrotes', 'und', array['und']::text[], array['Bocadillo enchilada de papa y carne', 'Bocadillos de papa y carne']::text[], true),
  ('prod-aba-253', 'main', 'ABA-253', 'Bocadillo de Piña', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos de Piña']::text[], true),
  ('prod-aba-226', 'main', 'ABA-226', 'Bocadillo de Pollo', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos de Pollo']::text[], true),
  ('prod-aba-221', 'main', 'ABA-221', 'Bocadillo Empanada de Pollo', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos Empanada de Pollo']::text[], true),
  ('prod-aba-219', 'main', 'ABA-219', 'Bocadillo Flauta C/ Mora', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos Flauta C/ Mora']::text[], true),
  ('prod-aba-119', 'main', 'ABA-119', 'Bocadillo Flauta de Maracuya', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos Flauta de Maracuya']::text[], true),
  ('prod-aba-218', 'main', 'ABA-218', 'Bocadillo Pañelito de Dulce de Leche', 'Abarrotes', 'und', array['und']::text[], array['Bocadillos Pañelito de Dulce de Leche']::text[], true),
  ('prod-aba-118', 'main', 'ABA-118', 'Canela Astilla 226 Grs', 'Abarrotes', 'und', array['und']::text[], array['Canela Astilla', 'Canelas Astilla']::text[], true),
  ('prod-aba-216', 'main', 'ABA-216', 'Cereal Hojuela Maiz C/chocol. 1/1.2 Kg', 'Abarrotes', 'und', array['und']::text[], array['Cereal Hojuela Maiz C/chocol. 1/', 'Cereales Hojuela Maiz C/chocol. 1/']::text[], true),
  ('prod-aba-215', 'main', 'ABA-215', 'Cereal Natural a Granel', 'Abarrotes', 'kg', array['kg']::text[], array['Cereales Natural a Granel']::text[], true),
  ('prod-aba-214', 'main', 'ABA-214', 'Cereal Raisin Bran', 'Abarrotes', 'paquete', array['paquete']::text[], array['Cereales Raisin Bran']::text[], true),
  ('prod-aba-213', 'main', 'ABA-213', 'Chile Chipotle', 'Abarrotes', 'und', array['und']::text[], array['Chiles Chipotle']::text[], true),
  ('prod-aba-211', 'main', 'ABA-211', 'Chile en escamas', 'Abarrotes', 'und', array['und']::text[], array['CHILE ESCAMAS', 'Chiles en escamas', 'CHILE EN ESCAMAS (340 GR)']::text[], true),
  ('prod-aba-108', 'main', 'ABA-108', 'Chile Jalapeño Mitades S/ en Rodajas', 'Abarrotes', 'envase', array['envase', 'kg']::text[], array['Chiles Jalapeño Mitades S/ en Rodajas']::text[], true),
  ('prod-aba-210', 'main', 'ABA-210', 'Chispas de Chocolate Hersheys', 'Abarrotes', 'paquete', array['paquete']::text[], array[]::text[], true),
  ('prod-aba-209', 'main', 'ABA-209', 'Coco Blanco Rayado 2 Kg', 'Abarrotes', 'paquete', array['paquete']::text[], array['Coco Blanco Rayado', 'Cocos Blanco Rayado']::text[], true),
  ('prod-aba-208', 'main', 'ABA-208', 'Cocoa Amarga Kilo', 'Abarrotes', 'kg', array['kg']::text[], array['Cocoa Amarga', 'Cocoas Amarga']::text[], true),
  ('prod-aba-207', 'main', 'ABA-207', 'Cocoa Dulce Instantaneo', 'Abarrotes', 'kg', array['kg']::text[], array['Cocoas Dulce Instantaneo']::text[], true),
  ('prod-aba-107', 'main', 'ABA-107', 'Consome de Pollo #1', 'Abarrotes', 'kg', array['kg']::text[], array['Consomes de Pollo #1']::text[], true),
  ('prod-aba-206', 'main', 'ABA-206', 'Consome Mariscos', 'Abarrotes', 'und', array['und']::text[], array['Consomes Mariscos']::text[], true),
  ('prod-aba-205', 'main', 'ABA-205', 'Consome Res 1/1kg', 'Abarrotes', 'und', array['und']::text[], array['Consome Res 1/', 'Consomes Res 1/']::text[], true),
  ('prod-aba-135', 'main', 'ABA-135', 'Crema de Coco Mamá 15 Oz', 'Abarrotes', 'und', array['und']::text[], array['Crema de Coco Mamá', 'Cremas de Coco Mamá']::text[], true),
  ('prod-aba-132', 'main', 'ABA-132', 'Crema Dulce Tetra Brik 1litro', 'Abarrotes', 'und', array['und']::text[], array['Crema Dulce Tetra Brik', 'Cremas Dulce Tetra Brik']::text[], true),
  ('prod-aba-204', 'main', 'ABA-204', 'Croissant de 65 Grs', 'Abarrotes', 'und', array['und']::text[], array['Croissant de', 'Croissantes de']::text[], true),
  ('prod-aba-203', 'main', 'ABA-203', 'Curry en Pasta ( Solicitud del Cheff )', 'Abarrotes', 'und', array['und']::text[], array['Curry en Pasta', 'Curryes en Pasta']::text[], true),
  ('prod-aba-137', 'main', 'ABA-137', 'Empanizador de Pollo', 'Abarrotes', 'kg', array['kg']::text[], array['Empanizadores de Pollo']::text[], true),
  ('prod-aba-202', 'main', 'ABA-202', 'Envoltura Papel 15x10 3/4 ( Papel Encerado )', 'Abarrotes', 'und', array['und']::text[], array['Envoltura Papel 15x10 3/4', 'Envolturas Papel 15x10 3/4']::text[], true),
  ('prod-aba-201', 'main', 'ABA-201', 'Frijoles Blancos Paq', 'Abarrotes', 'paquete', array['paquete', 'kg']::text[], array['Frijoles Blancos']::text[], true),
  ('prod-aba-136', 'main', 'ABA-136', 'Frijoles Rojo Don Pedro 2,0', 'Abarrotes', 'paquete', array['paquete']::text[], array[]::text[], true),
  ('prod-aba-200', 'main', 'ABA-200', 'Garbanzos en Paquete', 'Abarrotes', 'paquete', array['paquete', 'kg']::text[], array['Garbanzos en']::text[], true),
  ('prod-aba-126', 'main', 'ABA-126', 'Garbanzos Lata', 'Abarrotes', 'lata', array['lata', 'kg']::text[], array[]::text[], true),
  ('prod-aba-199', 'main', 'ABA-199', 'Granola Lustig Receta Casera', 'Abarrotes', 'kg', array['kg']::text[], array['Granolas Lustig Receta Casera']::text[], true),
  ('prod-aba-198', 'main', 'ABA-198', 'Harina Estandar 25 Kg', 'Abarrotes', 'bulto', array['bulto']::text[], array['Harina Estandar', 'Harinas Estandar']::text[], true),
  ('prod-aba-197', 'main', 'ABA-197', 'Hierbas de Provenza', 'Abarrotes', 'frasco', array['frasco', 'und']::text[], array['Hierbas de Provincia', 'hierbas provenzales']::text[], true),
  ('prod-aba-100', 'main', 'ABA-100', 'Hongos Rebanados Enlatados 2.840 Kg', 'Abarrotes', 'galón', array['galón']::text[], array['Hongos Rebanados Enlatados']::text[], true),
  ('prod-aba-196', 'main', 'ABA-196', 'Jalea Indiv D 4 Sabores 1/200 Und', 'Abarrotes', 'und', array['und']::text[], array['Jalea Indiv D 4 Sabores 1/', 'Jaleas Indiv D 4 Sabores 1/']::text[], true),
  ('prod-aba-127', 'main', 'ABA-127', 'Jengibre para Sushi Tipo Gari Japones', 'Abarrotes', 'und', array['und']::text[], array['Geingibre Para sushi tipo Gary Japones', 'Jengibres para Sushi Tipo Gari Japones']::text[], true),
  ('prod-aba-195', 'main', 'ABA-195', 'Jugo de Tomate C/chile 157 Ml (sin Chile)', 'Abarrotes', 'und', array['und']::text[], array['Jugo de Tomate C/chile', 'Jugos de Tomate C/chile']::text[], true),
  ('prod-aba-194', 'main', 'ABA-194', 'Lasagna Roma', 'Abarrotes', 'paquete', array['paquete', 'g']::text[], array['Lasagnas Roma']::text[], true),
  ('prod-aba-001', 'main', 'ABA-001', 'Leche', 'Abarrotes', 'caja', array['caja', 'L', 'botella', 'paquete']::text[], array['leches', 'caja de leche', 'cajas de leche']::text[], true),
  ('prod-aba-193', 'main', 'ABA-193', 'Leche de Coco en Lata', 'Abarrotes', 'und', array['und']::text[], array['Leches de Coco en Lata']::text[], true),
  ('prod-aba-102', 'main', 'ABA-102', 'Leche Entera 3,5% Foodie 1/12 Lt', 'Abarrotes', 'und', array['und']::text[], array['Leche Entera 3,5% Foodie 1/', 'Leches Entera 3,5% Foodie 1/']::text[], true),
  ('prod-aba-117', 'main', 'ABA-117', 'Leche Evaporada', 'Abarrotes', 'L', array['L']::text[], array['Leches Evaporada']::text[], true),
  ('prod-aba-192', 'main', 'ABA-192', 'Leche Soya Organica S/azucar', 'Abarrotes', 'envase', array['envase']::text[], array['Leches Soya Organica S/azucar']::text[], true),
  ('prod-aba-191', 'main', 'ABA-191', 'Lentejas Paquete', 'Abarrotes', 'paquete', array['paquete']::text[], array['Lentejas']::text[], true),
  ('prod-aba-190', 'main', 'ABA-190', 'Levadura Dulce Seca (unidad)', 'Abarrotes', 'und', array['und']::text[], array['Levadura Dulce Seca', 'Levaduras Dulce Seca']::text[], true),
  ('prod-aba-189', 'main', 'ABA-189', 'Levadura Salada Seca', 'Abarrotes', 'und', array['und']::text[], array['Levaduras Salada Seca']::text[], true),
  ('prod-aba-188', 'main', 'ABA-188', 'Lomo Churrasco', 'Abarrotes', 'kg', array['kg']::text[], array['Lomos Churrasco']::text[], true),
  ('prod-aba-114', 'main', 'ABA-114', 'Maiz Dulce Lata 3kg', 'Abarrotes', 'und', array['und']::text[], array['Maiz Dulce Lata', 'Maices Dulce Lata']::text[], true),
  ('prod-aba-187', 'main', 'ABA-187', 'Maizena', 'Abarrotes', 'paquete', array['paquete']::text[], array['Maizenas']::text[], true),
  ('prod-aba-186', 'main', 'ABA-186', 'Mani Picado Kilo', 'Abarrotes', 'kg', array['kg']::text[], array['Mani Picado', 'Manis Picado']::text[], true),
  ('prod-aba-185', 'main', 'ABA-185', 'Mantequilla sin Sal', 'Abarrotes', 'kg', array['kg']::text[], array['Mantequillas sin Sal']::text[], true),
  ('prod-aba-184', 'main', 'ABA-184', 'Masa de Maiz Amarilla Doña Arepa', 'Abarrotes', 'kg', array['kg']::text[], array['Masas de Maiz Amarilla Doña Arepa']::text[], true),
  ('prod-aba-183', 'main', 'ABA-183', 'Maseca 907 Grs', 'Abarrotes', 'paquete', array['paquete']::text[], array['Maseca', 'Masecas']::text[], true),
  ('prod-aba-101', 'main', 'ABA-101', 'Mayonesa Galon', 'Abarrotes', 'galón', array['galón']::text[], array['Mayonesa', 'Mayonesas']::text[], true),
  ('prod-aba-182', 'main', 'ABA-182', 'Mayonesa Individual en Sobres', 'Abarrotes', 'caja', array['caja', 'und']::text[], array['Mayonesas Individual en Sobres']::text[], true),
  ('prod-aba-129', 'main', 'ABA-129', 'Mermelada Balde 4,5 Kg Galon Guayaba', 'Abarrotes', 'galón', array['galón']::text[], array['Mermelada Balde', 'Mermeladas Balde']::text[], true),
  ('prod-aba-181', 'main', 'ABA-181', 'Mermelada Fresa 2,0', 'Abarrotes', 'galón', array['galón']::text[], array['Mermeladas Fresa 2,0']::text[], true),
  ('prod-aba-180', 'main', 'ABA-180', 'Mermelada Mora 2,0', 'Abarrotes', 'galón', array['galón']::text[], array['Mermeladas Mora 2,0']::text[], true),
  ('prod-aba-116', 'main', 'ABA-116', 'Mermelada Piña 2,0', 'Abarrotes', 'galón', array['galón']::text[], array['Mermeladas Piña 2,0']::text[], true),
  ('prod-aba-113', 'main', 'ABA-113', 'Mezcla Completa P/panqueques 2,0', 'Abarrotes', 'paquete', array['paquete', 'kg']::text[], array['Mezclas Completa P/panqueques 2,0']::text[], true),
  ('prod-aba-179', 'main', 'ABA-179', 'Miel de Abeja', 'Abarrotes', 'botella', array['botella']::text[], array['Mieles de Abeja']::text[], true),
  ('prod-aba-259', 'main', 'ABA-259', 'Mini Muffin de Vainilla', 'Abarrotes', 'und', array['und']::text[], array['Minis Muffin de Vainilla']::text[], true),
  ('prod-aba-263', 'main', 'ABA-263', 'Mostaza Galon', 'Abarrotes', 'galón', array['galón']::text[], array['Mostaza', 'Mostazas']::text[], true),
  ('prod-aba-256', 'main', 'ABA-256', 'Muffin de Chocolate', 'Abarrotes', 'und', array['und']::text[], array['Muffines de Chocolate']::text[], true),
  ('prod-aba-177', 'main', 'ABA-177', 'Nachos de Maiz con Sal', 'Abarrotes', 'und', array['und']::text[], array[]::text[], true),
  ('prod-aba-115', 'main', 'ABA-115', 'Palmito Entero Enlatado', 'Abarrotes', 'galón', array['galón']::text[], array['Palmitos Entero Enlatado']::text[], true),
  ('prod-aba-176', 'main', 'ABA-176', 'Pan Cena', 'Abarrotes', 'paquete', array['paquete']::text[], array['Panes Cena']::text[], true),
  ('prod-aba-140', 'main', 'ABA-140', 'Paprika', 'Abarrotes', 'frasco', array['frasco']::text[], array['Paprikas']::text[], true),
  ('prod-aba-175', 'main', 'ABA-175', 'Pasas Kilo', 'Abarrotes', 'kg', array['kg']::text[], array['Pasas']::text[], true),
  ('prod-aba-146', 'main', 'ABA-146', 'Pasta Caracolitos', 'Abarrotes', 'kg', array['kg']::text[], array['Pastas Caracolitos']::text[], true),
  ('prod-aba-144', 'main', 'ABA-144', 'Pasta Coditos', 'Abarrotes', 'kg', array['kg']::text[], array['Pastas Coditos']::text[], true),
  ('prod-aba-124', 'main', 'ABA-124', 'Pasta de Tomate Old Calif 3.14 Kg', 'Abarrotes', 'kg', array['kg']::text[], array['Pasta de Tomate Old Calif', 'Pastas de Tomate Old Calif']::text[], true),
  ('prod-aba-174', 'main', 'ABA-174', 'Pasta Fetuchinne )( Tallarin )', 'Abarrotes', 'kg', array['kg']::text[], array['Pasta Fetuchinne )', 'Pastas Fetuchinne )']::text[], true),
  ('prod-aba-173', 'main', 'ABA-173', 'Pasta Penne Rigatte (plumas)', 'Abarrotes', 'kg', array['kg']::text[], array['Pasta Penne Rigatte', 'Pastas Penne Rigatte']::text[], true),
  ('prod-aba-134', 'main', 'ABA-134', 'Pasta Spaguetti Kg', 'Abarrotes', 'kg', array['kg']::text[], array['Pasta Spaguetti', 'Pastas Spaguetti']::text[], true),
  ('prod-aba-172', 'main', 'ABA-172', 'Pasta wasabi', 'Abarrotes', 'und', array['und']::text[], array['Pastas wasabi']::text[], true),
  ('prod-aba-171', 'main', 'ABA-171', 'Pejiballes Enteros', 'Abarrotes', 'galón', array['galón']::text[], array[]::text[], true),
  ('prod-aba-170', 'main', 'ABA-170', 'Pepinillos Rebanados Galon', 'Abarrotes', 'galón', array['galón']::text[], array['Pepinillos Rebanados']::text[], true),
  ('prod-aba-168', 'main', 'ABA-168', 'Quinoa Blanca', 'Abarrotes', 'und', array['und']::text[], array['Quinoas Blanca']::text[], true),
  ('prod-aba-169', 'main', 'ABA-169', 'Quinoa Roja 2,0', 'Abarrotes', 'und', array['und']::text[], array['Quinoas Roja 2,0']::text[], true),
  ('prod-aba-111', 'main', 'ABA-111', 'Sal Refinada Paq 1 Kilo', 'Abarrotes', 'kg', array['kg']::text[], array['Sal Refinada', 'Sales Refinada']::text[], true),
  ('prod-aba-142', 'main', 'ABA-142', 'Salsa Bbq Regular', 'Abarrotes', 'galón', array['galón']::text[], array['Salsas Bbq Regular']::text[], true),
  ('prod-aba-167', 'main', 'ABA-167', 'Salsa Bufalo', 'Abarrotes', 'und', array['und']::text[], array['Salsas Bufalo']::text[], true),
  ('prod-aba-166', 'main', 'ABA-166', 'Salsa China Galon', 'Abarrotes', 'galón', array['galón']::text[], array['Salsa China', 'Salsas China']::text[], true),
  ('prod-aba-128', 'main', 'ABA-128', 'Salsa de Tomate Galon', 'Abarrotes', 'galón', array['galón']::text[], array['Salsa de Tomate', 'Salsas de Tomate']::text[], true),
  ('prod-aba-165', 'main', 'ABA-165', 'Salsa de Tomate Individual', 'Abarrotes', 'caja', array['caja']::text[], array['Salsas de Tomate Individual']::text[], true),
  ('prod-aba-164', 'main', 'ABA-164', 'Salsa Demiglace Gourmet 1.2 Kg', 'Abarrotes', 'und', array['und']::text[], array['Salsa Demiglace Gourmet', 'Salsas Demiglace Gourmet']::text[], true),
  ('prod-aba-143', 'main', 'ABA-143', 'Salsa Inglesa ( Lizano ) Galon', 'Abarrotes', 'galón', array['galón']::text[], array['Salsa Inglesa', 'Salsas Inglesa']::text[], true),
  ('prod-aba-163', 'main', 'ABA-163', 'Salsa Queso Cheddar Sysco 3.03 Kg', 'Abarrotes', 'galón', array['galón']::text[], array['Salsa Queso Cheddar Sysco', 'Salsas Queso Cheddar Sysco']::text[], true),
  ('prod-aba-130', 'main', 'ABA-130', 'Salsa Soya Ligth 2.0', 'Abarrotes', 'galón', array['galón']::text[], array['Salsas Soya Ligth 2.0', 'salsa soya light', 'soya ligera']::text[], true),
  ('prod-aba-162', 'main', 'ABA-162', 'Salsa Teriyaki Sauce Culinaire', 'Abarrotes', 'galón', array['galón']::text[], array['Salsas Teriyaki Sauce Culinaire']::text[], true),
  ('prod-aba-112', 'main', 'ABA-112', 'Sazonador Completa 2,0', 'Abarrotes', 'und', array['und']::text[], array['Sazonadores Completa 2,0']::text[], true),
  ('prod-aba-161', 'main', 'ABA-161', 'Sirope Caramelo Hersheys', 'Abarrotes', 'und', array['und']::text[], array['Siropes Caramelo Hersheys']::text[], true),
  ('prod-aba-141', 'main', 'ABA-141', 'Sirope Chocolate Hersheys', 'Abarrotes', 'und', array['und']::text[], array['Siropes Chocolate Hersheys']::text[], true),
  ('prod-aba-160', 'main', 'ABA-160', 'Sirope de Kola Rojo', 'Abarrotes', 'galón', array['galón']::text[], array['Siropes de Kola Rojo']::text[], true),
  ('prod-aba-159', 'main', 'ABA-159', 'Sirope para Panqueque Galon', 'Abarrotes', 'galón', array['galón']::text[], array['Sirope para Panqueque', 'Siropes para Panqueque']::text[], true),
  ('prod-aba-251', 'main', 'ABA-251', 'Sriracha', 'Abarrotes', 'botella', array['botella']::text[], array['SIRACHA', 'Srirachas']::text[], true),
  ('prod-aba-158', 'main', 'ABA-158', 'Tabasco ( Lizano ) Bot 62 Grs', 'Abarrotes', 'und', array['und']::text[], array['Tabasco', 'Tabascos']::text[], true),
  ('prod-aba-157', 'main', 'ABA-157', 'Te 4 Frutas', 'Abarrotes', 'und', array['und']::text[], array['Tes 4 Frutas']::text[], true),
  ('prod-aba-156', 'main', 'ABA-156', 'Te de Menta', 'Abarrotes', 'und', array['und']::text[], array['Tes de Menta']::text[], true),
  ('prod-aba-155', 'main', 'ABA-155', 'Te Manzanilla Caja 100 U', 'Abarrotes', 'und', array['und']::text[], array['Te Manzanilla', 'Tes Manzanilla']::text[], true),
  ('prod-aba-154', 'main', 'ABA-154', 'Te Negro Selecto', 'Abarrotes', 'paquete', array['paquete']::text[], array['Tes Negro Selecto']::text[], true),
  ('prod-aba-153', 'main', 'ABA-153', 'Te Verde', 'Abarrotes', 'caja', array['caja']::text[], array['Tes Verde']::text[], true),
  ('prod-aba-152', 'main', 'ABA-152', 'Vinagre Balsamico Aceto Di Modena', 'Abarrotes', 'galón', array['galón']::text[], array['Vinagres Balsamico Aceto Di Modena']::text[], true),
  ('prod-aba-151', 'main', 'ABA-151', 'Vinagre Blanco Sintetico Galon', 'Abarrotes', 'galón', array['galón']::text[], array['Vinagre Blanco Sintetico', 'Vinagres Blanco Sintetico']::text[], true),
  ('prod-aba-145', 'main', 'ABA-145', 'Vinagre de Arroz Marukan', 'Abarrotes', 'galón', array['galón']::text[], array['Vinagres de Arroz Marukan']::text[], true),
  ('prod-aba-150', 'main', 'ABA-150', 'Vino Blanco Tetrabick', 'Abarrotes', 'L', array['L']::text[], array['Vinos Blanco Tetrabick']::text[], true),
  ('prod-aba-149', 'main', 'ABA-149', 'Vino Tinto Tetrabrick', 'Abarrotes', 'L', array['L']::text[], array['Vinos Tinto Tetrabrick']::text[], true),
  ('prod-aba-147', 'main', 'ABA-147', 'Vol au vent', 'Abarrotes', 'und', array['und']::text[], array['VOLAUVENT', 'Voles au vent', 'volován', 'volovanes']::text[], true),
  ('prod-fv-001', 'main', 'FV-001', 'Aguacate Hass', 'Frutas y vegetales', 'kg', array['kg']::text[], array['aguacates hass']::text[], true),
  ('prod-fv-002', 'main', 'FV-002', 'Ají amarillo peruano', 'Frutas y vegetales', 'kg', array['kg']::text[], array['ají amarillo', 'chile amarillo peruano', 'Ajís amarillo peruano']::text[], true),
  ('prod-fv-003', 'main', 'FV-003', 'Ajo entero con cáscara', 'Frutas y vegetales', 'kg', array['kg']::text[], array['ajo cabeza', 'ajo sin pelar', 'Ajos entero con cáscara']::text[], true),
  ('prod-fv-004', 'main', 'FV-004', 'Ajo pelado', 'Frutas y vegetales', 'kg', array['kg']::text[], array['ajo limpio', 'Ajos pelado']::text[], true),
  ('prod-fv-005', 'main', 'FV-005', 'Albahaca fresca', 'Frutas y vegetales', 'kg', array['kg']::text[], array['albahaca', 'albahaca fresca rollo', 'Albahacas fresca']::text[], true),
  ('prod-fv-006', 'main', 'FV-006', 'Apio', 'Frutas y vegetales', 'kg', array['kg']::text[], array['apio kg', 'Apios']::text[], true),
  ('prod-fv-099', 'main', 'FV-099', 'Arándanos', 'Frutas y vegetales', 'g', array['g']::text[], array['blueberries']::text[], true),
  ('prod-fv-007', 'main', 'FV-007', 'Ayote sazón', 'Frutas y vegetales', 'kg', array['kg']::text[], array['Ayotes sazón']::text[], true),
  ('prod-fru-001', 'main', 'FRU-001', 'Banano', 'Frutas y vegetales', 'und', array['und', 'kg']::text[], array['bananos', 'banana', 'bananas']::text[], true),
  ('prod-fv-009', 'main', 'FV-009', 'Berenjena', 'Frutas y vegetales', 'und', array['und']::text[], array['berengena', 'berenjenas']::text[], true),
  ('prod-fv-010', 'main', 'FV-010', 'Bok choy', 'Frutas y vegetales', 'rollo', array['rollo']::text[], array['pak choi', 'pack choy', 'bock choy', 'bok choi', 'Bokes choy']::text[], true),
  ('prod-fv-011', 'main', 'FV-011', 'Brócoli', 'Frutas y vegetales', 'kg', array['kg']::text[], array['Brócolis']::text[], true),
  ('prod-fv-012', 'main', 'FV-012', 'Camote', 'Frutas y vegetales', 'kg', array['kg']::text[], array['camotes']::text[], true),
  ('prod-fv-013', 'main', 'FV-013', 'Cebolla blanca', 'Frutas y vegetales', 'kg', array['kg']::text[], array['cebolla blanca kg', 'Cebollas blanca']::text[], true),
  ('prod-fv-014', 'main', 'FV-014', 'Cebolla morada', 'Frutas y vegetales', 'kg', array['kg']::text[], array['cebolla morada kg', 'Cebollas morada']::text[], true),
  ('prod-fv-015', 'main', 'FV-015', 'Cebollín', 'Frutas y vegetales', 'rollo', array['rollo']::text[], array['cebollino con cabeza', 'Cebollines']::text[], true),
  ('prod-fv-037', 'main', 'FV-037', 'Champiñón entero', 'Frutas y vegetales', 'cápsula', array['cápsula']::text[], array['hongo champiñón', 'champignon entero', 'champiñones enteros', 'Champinones entero']::text[], true),
  ('prod-fv-016', 'main', 'FV-016', 'Chayote tierno quelite', 'Frutas y vegetales', 'und', array['und']::text[], array['chayote tierno', 'chayote quelite', 'quellite', 'Chayotes tierno quelite']::text[], true),
  ('prod-fv-017', 'main', 'FV-017', 'Chile dulce de segunda', 'Frutas y vegetales', 'und', array['und']::text[], array['chile dulce segunda', 'Chiles dulce de segunda']::text[], true),
  ('prod-fv-018', 'main', 'FV-018', 'Chile guajillo', 'Frutas y vegetales', 'kg', array['kg']::text[], array['guajillo', 'Chiles guajillo']::text[], true),
  ('prod-fv-019', 'main', 'FV-019', 'Chile jalapeño', 'Frutas y vegetales', 'kg', array['kg']::text[], array['jalapeño', 'Chiles jalapeño']::text[], true),
  ('prod-fv-020', 'main', 'FV-020', 'Chile panameño', 'Frutas y vegetales', 'kg', array['kg']::text[], array['Chiles panameño']::text[], true),
  ('prod-fv-021', 'main', 'FV-021', 'Chiverre grande', 'Frutas y vegetales', 'und', array['und']::text[], array['chiverry', 'chiverre', 'Chiverres grande']::text[], true),
  ('prod-fv-098', 'main', 'FV-098', 'Ciboulette', 'Frutas y vegetales', 'paquete', array['paquete']::text[], array['cibullet', 'cebollino fino', 'cebollín francés', 'Ciboulettes']::text[], true),
  ('prod-fv-022', 'main', 'FV-022', 'Ciruela', 'Frutas y vegetales', 'kg', array['kg']::text[], array['ciruelas']::text[], true),
  ('prod-fv-023', 'main', 'FV-023', 'Coco', 'Frutas y vegetales', 'und', array['und']::text[], array['cocos']::text[], true),
  ('prod-fv-024', 'main', 'FV-024', 'Coliflor', 'Frutas y vegetales', 'und', array['und']::text[], array['coliflores']::text[], true),
  ('prod-fv-025', 'main', 'FV-025', 'Culantro coyote', 'Frutas y vegetales', 'tamuga', array['tamuga']::text[], array['culantro coyote 30 gramos', 'Culantros coyote']::text[], true),
  ('prod-fv-026', 'main', 'FV-026', 'Culantro de Castilla', 'Frutas y vegetales', 'tamuga', array['tamuga']::text[], array['culantro popular', 'culantro castilla', 'culantro de castilla 30 gramos', 'Culantros de Castilla']::text[], true),
  ('prod-fv-027', 'main', 'FV-027', 'Elote blanco', 'Frutas y vegetales', 'und', array['und']::text[], array['elotes blancos', 'Elotes blanco']::text[], true),
  ('prod-fv-028', 'main', 'FV-028', 'Elote dulce amarillo', 'Frutas y vegetales', 'bandeja', array['bandeja']::text[], array['elote amarillo', 'elote dulce', 'Elotes dulce amarillo']::text[], true),
  ('prod-fv-029', 'main', 'FV-029', 'Eneldo', 'Frutas y vegetales', 'rollo', array['rollo']::text[], array['eneldo fresco', 'Eneldos']::text[], true),
  ('prod-fv-030', 'main', 'FV-030', 'Espinaca deshojada', 'Frutas y vegetales', 'kg', array['kg']::text[], array['espinaca desojada', 'espinaca hojas', 'Espinacas deshojada']::text[], true),
  ('prod-fv-038', 'main', 'FV-038', 'Flor de Jamaica', 'Frutas y vegetales', 'g', array['g']::text[], array['jamaica', 'flor de jamaica seca', 'Flores de Jamaica']::text[], true),
  ('prod-fv-031', 'main', 'FV-031', 'Fresa', 'Frutas y vegetales', 'bandeja', array['bandeja', 'und']::text[], array['fresas']::text[], true),
  ('prod-fv-032', 'main', 'FV-032', 'Frijol tierno', 'Frutas y vegetales', 'kg', array['kg']::text[], array['frijoles tiernos', 'Frijoles tierno']::text[], true),
  ('prod-fv-033', 'main', 'FV-033', 'Granadilla', 'Frutas y vegetales', 'kg', array['kg']::text[], array['granadillas']::text[], true),
  ('prod-fv-034', 'main', 'FV-034', 'Hierbabuena', 'Frutas y vegetales', 'bolsa', array['bolsa']::text[], array['hierba buena', 'hierbabuena 100 gramos', 'Hierbabuenas']::text[], true),
  ('prod-fv-035', 'main', 'FV-035', 'Hojas de chicasquil', 'Frutas y vegetales', 'g', array['g']::text[], array['chicasquil', 'hojas chicasquil']::text[], true),
  ('prod-fv-036', 'main', 'FV-036', 'Hojas de plátano para tamal', 'Frutas y vegetales', 'kg', array['kg']::text[], array['hojas de platano', 'hojas para tamal']::text[], true),
  ('prod-fv-039', 'main', 'FV-039', 'Jengibre', 'Frutas y vegetales', 'kg', array['kg']::text[], array['jengibres']::text[], true),
  ('prod-fv-040', 'main', 'FV-040', 'Kale morado', 'Frutas y vegetales', 'kg', array['kg']::text[], array['col rizada morada', 'Kales morado']::text[], true),
  ('prod-fv-041', 'main', 'FV-041', 'Lechuga americana hidropónica', 'Frutas y vegetales', 'und', array['und']::text[], array['lechuga americana', 'lechuga hidroponica', 'Lechugas americana hidropónica']::text[], true),
  ('prod-fv-043', 'main', 'FV-043', 'Lechuga baby variada', 'Frutas y vegetales', 'kg', array['kg']::text[], array['lechuga variedad baby', 'mix de lechuga baby', 'Lechugas baby variada']::text[], true),
  ('prod-fv-042', 'main', 'FV-042', 'Lechuga escarola', 'Frutas y vegetales', 'und', array['und']::text[], array['escarola', 'Lechugas escarola']::text[], true),
  ('prod-fv-044', 'main', 'FV-044', 'Limón mesino', 'Frutas y vegetales', 'und', array['und']::text[], array['limón criollo', 'Limones mesino']::text[], true),
  ('prod-fv-045', 'main', 'FV-045', 'Maíz cascado', 'Frutas y vegetales', 'kg', array['kg']::text[], array['Maíces cascado']::text[], true),
  ('prod-fv-046', 'main', 'FV-046', 'Mamón chino', 'Frutas y vegetales', 'kg', array['kg']::text[], array['rambután', 'Mamones chino']::text[], true),
  ('prod-fv-048', 'main', 'FV-048', 'Mandarina nacional', 'Frutas y vegetales', 'kg', array['kg']::text[], array['mandarinas nacionales', 'Mandarinas nacional']::text[], true),
  ('prod-fv-049', 'main', 'FV-049', 'Manga pintona', 'Frutas y vegetales', 'kg', array['kg']::text[], array['mango pintón', 'Mangas pintona']::text[], true),
  ('prod-fv-050', 'main', 'FV-050', 'Manzana Gala nacional económica calibre 150', 'Frutas y vegetales', 'kg', array['kg']::text[], array['manzana gala nacional', 'manzana gala 150', 'Manzanas Gala nacional económica calibre 150']::text[], true),
  ('prod-fv-051', 'main', 'FV-051', 'Manzana Granny Smith grande calibre 170', 'Frutas y vegetales', 'kg', array['kg']::text[], array['manzana granny', 'manzana verde grande', 'granny smith 170', 'Manzanas Granny Smith grande calibre 170']::text[], true),
  ('prod-fv-047', 'main', 'FV-047', 'Manzana Red calibre 150', 'Frutas y vegetales', 'kg', array['kg']::text[], array['manzana red 150', 'manzana roja calibre 150', 'Manzanas Red calibre 150']::text[], true),
  ('prod-fv-052', 'main', 'FV-052', 'Maracuyá', 'Frutas y vegetales', 'und', array['und']::text[], array['frutas de la pasión', 'Maracuyás']::text[], true),
  ('prod-fru-005', 'main', 'FRU-005', 'Melón', 'Frutas y vegetales', 'kg', array['kg', 'und']::text[], array['melones']::text[], true),
  ('prod-fv-054', 'main', 'FV-054', 'Microgreens Vertigreens', 'Frutas y vegetales', 'caja', array['caja']::text[], array['micro greens', 'microgreens', 'mizuna roja', 'mizuna verde', 'brote de remolacha']::text[], true),
  ('prod-fv-055', 'main', 'FV-055', 'Mini escalopín amarillo', 'Frutas y vegetales', 'kg', array['kg']::text[], array['escalopin amarillo', 'mini squash amarillo', 'Minis escalopín amarillo']::text[], true),
  ('prod-fv-095', 'main', 'FV-095', 'Mini zanahoria heirloom', 'Frutas y vegetales', 'bandeja', array['bandeja']::text[], array['zanahoria heirloom', 'zanahoria de colores', 'Minis zanahoria heirloom']::text[], true),
  ('prod-fv-056', 'main', 'FV-056', 'Mora grande', 'Frutas y vegetales', 'cápsula', array['cápsula']::text[], array['moras grandes', 'Moras grande']::text[], true),
  ('prod-fv-057', 'main', 'FV-057', 'Mostaza china', 'Frutas y vegetales', 'und', array['und']::text[], array['mostaza oriental', 'Mostazas china']::text[], true),
  ('prod-fv-058', 'main', 'FV-058', 'Naranja importada premium', 'Frutas y vegetales', 'und', array['und']::text[], array['naranja importada', 'naranja premium', 'Naranjas importada premium']::text[], true),
  ('prod-fv-059', 'main', 'FV-059', 'Nectarina', 'Frutas y vegetales', 'kg', array['kg']::text[], array['nectarinas']::text[], true),
  ('prod-fv-060', 'main', 'FV-060', 'Ñame', 'Frutas y vegetales', 'kg', array['kg']::text[], array['Ñames']::text[], true),
  ('prod-fv-061', 'main', 'FV-061', 'Orégano fresco', 'Frutas y vegetales', 'rollo', array['rollo']::text[], array['oregano', 'Oréganos fresco']::text[], true),
  ('prod-fv-062', 'main', 'FV-062', 'Papa blanca', 'Frutas y vegetales', 'kg', array['kg']::text[], array['papas blancas', 'Papas blanca']::text[], true),
  ('prod-fv-063', 'main', 'FV-063', 'Papa semilla mini', 'Frutas y vegetales', 'kg', array['kg']::text[], array['papa mini', 'papa semilla', 'Papas semilla mini']::text[], true),
  ('prod-fru-003', 'main', 'FRU-003', 'Papaya madura', 'Frutas y vegetales', 'kg', array['kg', 'und']::text[], array['papaya', 'papayas maduras', 'Papayas madura']::text[], true),
  ('prod-fv-065', 'main', 'FV-065', 'Pejibaye cocinado', 'Frutas y vegetales', 'kg', array['kg']::text[], array['pejiballe', 'pejibaye', 'Pejibayes cocinado']::text[], true),
  ('prod-fv-066', 'main', 'FV-066', 'Pepino', 'Frutas y vegetales', 'kg', array['kg']::text[], array['pepinos']::text[], true),
  ('prod-fv-067', 'main', 'FV-067', 'Pera mini calibre 120', 'Frutas y vegetales', 'und', array['und']::text[], array['peras mini', 'pera 120', 'Peras mini calibre 120']::text[], true),
  ('prod-fv-068', 'main', 'FV-068', 'Perejil fresco', 'Frutas y vegetales', 'rollo', array['rollo']::text[], array['perejil', 'perejil rollo', 'Perejiles fresco']::text[], true),
  ('prod-fv-069', 'main', 'FV-069', 'Piña', 'Frutas y vegetales', 'und', array['und']::text[], array['piñas']::text[], true),
  ('prod-fru-004', 'main', 'FRU-004', 'Plátano maduro', 'Frutas y vegetales', 'und', array['und', 'kg']::text[], array['plátanos maduros', 'maduros', 'Plátanos maduro']::text[], true),
  ('prod-fv-071', 'main', 'FV-071', 'Plátano verde', 'Frutas y vegetales', 'und', array['und']::text[], array['plátanos verdes', 'Plátanos verde']::text[], true),
  ('prod-fv-072', 'main', 'FV-072', 'Rabanito tierno pequeño', 'Frutas y vegetales', 'rollo', array['rollo']::text[], array['rabanitos', 'rábano pequeño', 'Rabanitos tierno pequeño']::text[], true),
  ('prod-fv-073', 'main', 'FV-073', 'Radicchio', 'Frutas y vegetales', 'und', array['und']::text[], array['radichio', 'Radicchios']::text[], true),
  ('prod-fv-074', 'main', 'FV-074', 'Remolacha', 'Frutas y vegetales', 'kg', array['kg']::text[], array['remolachas']::text[], true),
  ('prod-fv-097', 'main', 'FV-097', 'Remolacha heirloom', 'Frutas y vegetales', 'g', array['g']::text[], array['remolacha heirlom', 'remolacha de colores', 'Remolachas heirloom']::text[], true),
  ('prod-fv-075', 'main', 'FV-075', 'Repollo morado', 'Frutas y vegetales', 'und', array['und']::text[], array['col morada', 'Repollos morado']::text[], true),
  ('prod-fv-076', 'main', 'FV-076', 'Repollo verde', 'Frutas y vegetales', 'und', array['und']::text[], array['repollo blanco', 'col verde', 'Repollos verde']::text[], true),
  ('prod-fv-077', 'main', 'FV-077', 'Romero fresco', 'Frutas y vegetales', 'rollo', array['rollo']::text[], array['romero', 'Romeros fresco']::text[], true),
  ('prod-fru-002', 'main', 'FRU-002', 'Sandía negra', 'Frutas y vegetales', 'kg', array['kg', 'und']::text[], array['sandía', 'Sandías negra']::text[], true),
  ('prod-fv-079', 'main', 'FV-079', 'Tacaco tierno', 'Frutas y vegetales', 'g', array['g']::text[], array['tacacos tiernos', 'Tacacos tierno']::text[], true),
  ('prod-fv-080', 'main', 'FV-080', 'Tapa de dulce', 'Frutas y vegetales', 'tamuga', array['tamuga']::text[], array['tapas de dulce', 'panela']::text[], true),
  ('prod-fv-081', 'main', 'FV-081', 'Tomate cherry uva a granel', 'Frutas y vegetales', 'kg', array['kg']::text[], array['tomate cherry', 'tomate uva', 'tomate uvita', 'Tomates cherry uva a granel']::text[], true),
  ('prod-fv-082', 'main', 'FV-082', 'Tomate de árbol', 'Frutas y vegetales', 'kg', array['kg']::text[], array['Tomates de árbol']::text[], true),
  ('prod-fv-083', 'main', 'FV-083', 'Tomate de tercera', 'Frutas y vegetales', 'kg', array['kg']::text[], array['tomate tercera', 'Tomates de tercera']::text[], true),
  ('prod-fv-096', 'main', 'FV-096', 'Tomate heirloom', 'Frutas y vegetales', 'kg', array['kg']::text[], array['tomate heirlom', 'tomate de herencia', 'Tomates heirloom']::text[], true),
  ('prod-fv-084', 'main', 'FV-084', 'Tomate verde mexicano', 'Frutas y vegetales', 'kg', array['kg']::text[], array['tomatillo', 'tomate verde', 'tomate mexicano', 'Tomates verde mexicano']::text[], true),
  ('prod-fv-085', 'main', 'FV-085', 'Tomillo fresco', 'Frutas y vegetales', 'bandeja', array['bandeja', 'und']::text[], array['tomillo', 'Tomillos fresco']::text[], true),
  ('prod-fv-086', 'main', 'FV-086', 'Uchuva pelada', 'Frutas y vegetales', 'bandeja', array['bandeja']::text[], array['uchuvas', 'uchuva 250 gramos', 'Uchuvas pelada']::text[], true),
  ('prod-fv-087', 'main', 'FV-087', 'Uva globo', 'Frutas y vegetales', 'kg', array['kg']::text[], array['uvas globo']::text[], true),
  ('prod-fv-088', 'main', 'FV-088', 'Uva verde sin semilla', 'Frutas y vegetales', 'kg', array['kg']::text[], array['uva verde', 'uvas verdes sin semilla', 'Uvas verde sin semilla']::text[], true),
  ('prod-fv-089', 'main', 'FV-089', 'Vainica mini', 'Frutas y vegetales', 'kg', array['kg']::text[], array['vainicas mini', 'judías verdes mini']::text[], true),
  ('prod-fv-090', 'main', 'FV-090', 'Yuca', 'Frutas y vegetales', 'kg', array['kg']::text[], array['yucas']::text[], true),
  ('prod-fv-091', 'main', 'FV-091', 'Zanahoria fresca', 'Frutas y vegetales', 'kg', array['kg']::text[], array['zanahorias', 'Zanahorias fresca']::text[], true),
  ('prod-fv-092', 'main', 'FV-092', 'Zanahoria mini', 'Frutas y vegetales', 'bandeja', array['bandeja']::text[], array['mini zanahoria', 'Zanahorias mini']::text[], true),
  ('prod-fv-093', 'main', 'FV-093', 'Zucchini', 'Frutas y vegetales', 'und', array['und']::text[], array['zuquiini', 'zuquini', 'calabacín', 'Zucchinis']::text[], true),
  ('prod-fv-094', 'main', 'FV-094', 'Zucchini mini bebé', 'Frutas y vegetales', 'bandeja', array['bandeja']::text[], array['zuquini mini', 'zucchini bebé', 'calabacín bebé', 'Zucchinis mini bebé']::text[], true),
  ('prod-pro-010', 'main', 'PRO-010', 'Alas de Pollo', 'Proteínas', 'kg', array['kg']::text[], array['alitas de pollo', 'alas']::text[], true),
  ('prod-pro-022', 'main', 'PRO-022', 'Atún Sushi Vietnan', 'Proteínas', 'kg', array['kg']::text[], array['Atunes Sushi Vietnan', 'atún para sushi', 'atún sushi', 'atún vietnam']::text[], true),
  ('prod-pro-003', 'main', 'PRO-003', 'Bistec Res', 'Proteínas', 'kg', array['kg']::text[], array['Bisteces Res', 'bistec de res', 'bistec']::text[], true),
  ('prod-pro-005', 'main', 'PRO-005', 'Camarón 2.5 Kg sin Cola', 'Proteínas', 'paquete', array['paquete', 'kg']::text[], array['Camarón', 'Camarones', 'camarón sin cola', 'camarones sin cola']::text[], true),
  ('prod-pro-017', 'main', 'PRO-017', 'Carne Molida', 'Proteínas', 'kg', array['kg']::text[], array['Carnes Molida', 'molida', 'carne de res molida']::text[], true),
  ('prod-pro-018', 'main', 'PRO-018', 'Costilla de Res Picado', 'Proteínas', 'kg', array['kg']::text[], array['Costillas de Res Picado', 'costilla de res picada', 'costilla de res']::text[], true),
  ('prod-pro-002', 'main', 'PRO-002', 'Fajitas de Pollo', 'Proteínas', 'kg', array['kg']::text[], array['pollo en fajitas', 'tiras de pollo']::text[], true),
  ('prod-pro-014', 'main', 'PRO-014', 'Fajitas de Res', 'Proteínas', 'kg', array['kg']::text[], array['res en fajitas', 'tiras de res']::text[], true),
  ('prod-pro-001', 'main', 'PRO-001', 'Filete de Pechuga de Pollo Fresco', 'Proteínas', 'kg', array['kg']::text[], array['FILET DE PECHUGA DE POLLO FRESCO', 'Filetes de Pechuga de Pollo Fresco', 'pechuga de pollo', 'filete de pollo', 'pechuga fresca']::text[], true),
  ('prod-pro-004', 'main', 'PRO-004', 'Filete Tilapia Kg 4,54 Kg Cada Caja', 'Proteínas', 'kg', array['kg']::text[], array['FILET TILAPIA KG 4,54 KG CADA CAJA', 'Filete Tilapia', 'Filetes Tilapia', 'filete de tilapia', 'tilapia']::text[], true),
  ('prod-pro-011', 'main', 'PRO-011', 'Lomito de Res', 'Proteínas', 'kg', array['kg']::text[], array['Lomitos de Res', 'lomito', 'filete de res']::text[], true),
  ('prod-pro-012', 'main', 'PRO-012', 'Lomo de Cerdo', 'Proteínas', 'kg', array['kg']::text[], array['Lomos de Cerdo', 'lomo cerdo']::text[], true),
  ('prod-pro-009', 'main', 'PRO-009', 'Mariscada Española 2,5 Kg ( Paq 500 Grs )', 'Proteínas', 'paquete', array['paquete', 'g']::text[], array['Mariscada Española', 'Mariscadas Española', 'mariscada']::text[], true),
  ('prod-pro-013', 'main', 'PRO-013', 'Muslo Entero', 'Proteínas', 'kg', array['kg']::text[], array['Muslos Entero', 'muslo de pollo', 'muslos enteros']::text[], true),
  ('prod-pro-006', 'main', 'PRO-006', 'Picadura de Corvina para Ceviche', 'Proteínas', 'kg', array['kg']::text[], array['Picaduras de Corvina para Ceviche', 'corvina para ceviche', 'picadura de corvina']::text[], true),
  ('prod-pro-016', 'main', 'PRO-016', 'Posta de Cerdo', 'Proteínas', 'kg', array['kg']::text[], array['Postas de Cerdo', 'posta cerdo']::text[], true),
  ('prod-pro-015', 'main', 'PRO-015', 'Quititena', 'Proteínas', 'kg', array['kg']::text[], array['Quititenas']::text[], true),
  ('prod-pro-019', 'main', 'PRO-019', 'Rib Eye Lipon Excel Choice ( 1 Pieza )', 'Proteínas', 'kg', array['kg']::text[], array['Rib Eye Lipon Excel Choice', 'Ribes Eye Lipon Excel Choice']::text[], true),
  ('prod-pro-021', 'main', 'PRO-021', 'Salmón Ahumado', 'Proteínas', 'kg', array['kg']::text[], array['Salmones Ahumado']::text[], true),
  ('prod-pro-007', 'main', 'PRO-007', 'Salmón Salar', 'Proteínas', 'kg', array['kg']::text[], array['Salmones Salar', 'salmón']::text[], true),
  ('prod-pro-008', 'main', 'PRO-008', 'Torta Angus', 'Proteínas', 'und', array['und']::text[], array['Tortas Angus', 'torta de res angus']::text[], true),
  ('prod-pro-020', 'main', 'PRO-020', 'Tortas P/ Hamburguesa Vegetarianas', 'Proteínas', 'und', array['und']::text[], array[]::text[], true),
  ('prod-ref-042', 'main', 'REF-042', 'Aros de Cebolla Empanicados', 'Refrigerados y congelados', 'caja', array['caja']::text[], array[]::text[], true),
  ('prod-ref-011', 'main', 'REF-011', 'Bocadillo de strudel de manzana', 'Refrigerados y congelados', 'und', array['und']::text[], array['Bocadillos de strudel de manzana']::text[], true),
  ('prod-ref-008', 'main', 'REF-008', 'Brownies Otis 2,0', 'Refrigerados y congelados', 'und', array['und']::text[], array[]::text[], true),
  ('prod-ref-012', 'main', 'REF-012', 'Cheesecake Fresa', 'Refrigerados y congelados', 'und', array['und']::text[], array['Cheesecakes Fresa']::text[], true),
  ('prod-ref-009', 'main', 'REF-009', 'Cheesecake Mora 10" 12porc. 1.5kg', 'Refrigerados y congelados', 'und', array['und']::text[], array['Cheesecake Mora 10"', 'Cheesecakes Mora 10"']::text[], true),
  ('prod-ref-038', 'main', 'REF-038', 'Chorizo Nobleza ( Cular ) 100 Grs Pen', 'Refrigerados y congelados', 'paquete', array['paquete', 'g']::text[], array['Chorizo Nobleza', 'Chorizos Nobleza']::text[], true),
  ('prod-ref-041', 'main', 'REF-041', 'Chorizo Precocido 600 Grs', 'Refrigerados y congelados', 'paquete', array['paquete', 'g']::text[], array['Chorizo Precocido', 'Chorizos Precocido']::text[], true),
  ('prod-ref-029', 'main', 'REF-029', 'Croissant ( Sándwich ) Grande 45 Grs', 'Refrigerados y congelados', 'und', array['und']::text[], array['CROISSANT ( SADWICH ) Grande 45 grs', 'Croissant Grande', 'Croissantes Grande']::text[], true),
  ('prod-ref-031', 'main', 'REF-031', 'Croqueta Yuca Precoc Large 6/1.5kg', 'Refrigerados y congelados', 'caja', array['caja']::text[], array['Croqueta Yuca Precoc Large 6/', 'Croquetas Yuca Precoc Large 6/']::text[], true),
  ('prod-ref-022', 'main', 'REF-022', 'Edamames', 'Refrigerados y congelados', 'paquete', array['paquete']::text[], array[]::text[], true),
  ('prod-ref-019', 'main', 'REF-019', 'Enyucado Carne', 'Refrigerados y congelados', 'paquete', array['paquete', 'kg']::text[], array['Enyucados Carne']::text[], true),
  ('prod-ref-032', 'main', 'REF-032', 'Galleta chispas de chocolate C1/100', 'Refrigerados y congelados', 'caja', array['caja']::text[], array['Galletas chispas de chocolate C1/100', 'galletas con chispas', 'galleta de chocolate', 'galletas choco chips', '330741 GALLETA CHISPAS DE CHOCOLATE C1/100']::text[], true),
  ('prod-ref-024', 'main', 'REF-024', 'Galleta Choco Chips Otis Caja 72 Unid', 'Refrigerados y congelados', 'caja', array['caja', 'und']::text[], array['Galleta Choco Chips Otis', 'Galletas Choco Chips Otis']::text[], true),
  ('prod-ref-033', 'main', 'REF-033', 'Galleta de Vainilla', 'Refrigerados y congelados', 'caja', array['caja']::text[], array['Galletas de Vainilla']::text[], true),
  ('prod-ref-020', 'main', 'REF-020', 'Hash-brown Ovalado', 'Refrigerados y congelados', 'caja', array['caja']::text[], array['Hash-brownes Ovalado']::text[], true),
  ('prod-ref-013', 'main', 'REF-013', 'Helado Vainilla', 'Refrigerados y congelados', 'cubeta', array['cubeta']::text[], array['Helados Vainilla']::text[], true),
  ('prod-ref-045', 'main', 'REF-045', 'Jalapeños Poppers', 'Refrigerados y congelados', 'paquete', array['paquete']::text[], array[]::text[], true),
  ('prod-ref-004', 'main', 'REF-004', 'Jamón Cocido Slq Grnr 1/500 Gr', 'Refrigerados y congelados', 'und', array['und']::text[], array['Jamón Cocido Slq Grnr 1/', 'Jamones Cocido Slq Grnr 1/']::text[], true),
  ('prod-ref-017', 'main', 'REF-017', 'Jamón de Pavo Light', 'Refrigerados y congelados', 'paquete', array['paquete', 'g']::text[], array['Jamones de Pavo Light']::text[], true),
  ('prod-ref-034', 'main', 'REF-034', 'Jamón Serrano Paq 500 Grs', 'Refrigerados y congelados', 'paquete', array['paquete', 'g']::text[], array['Jamón Serrano', 'Jamones Serrano']::text[], true),
  ('prod-ref-035', 'main', 'REF-035', 'Margarina en Bloques', 'Refrigerados y congelados', 'caja', array['caja']::text[], array['Margarinas en Bloques']::text[], true),
  ('prod-ref-030', 'main', 'REF-030', 'Mini croissant', 'Refrigerados y congelados', 'und', array['und', 'caja']::text[], array['MINI CROISSANT Pequeños', 'Minis croissant']::text[], true),
  ('prod-ref-043', 'main', 'REF-043', 'Mozzarella Sticks Palitos 1.8', 'Refrigerados y congelados', 'paquete', array['paquete']::text[], array['Mozzarellas Sticks Palitos 1.8']::text[], true),
  ('prod-ref-014', 'main', 'REF-014', 'Natilla', 'Refrigerados y congelados', 'galón', array['galón']::text[], array['Natillas']::text[], true),
  ('prod-ref-006', 'main', 'REF-006', 'Papa Everycrisp Covertura', 'Refrigerados y congelados', 'caja', array['caja', 'kg']::text[], array['Papas Everycrisp Covertura']::text[], true),
  ('prod-ref-010', 'main', 'REF-010', 'Pastel Chocolate 1/1.6 Kg', 'Refrigerados y congelados', 'und', array['und']::text[], array['Pastel Chocolate 1/', 'Pasteles Chocolate 1/']::text[], true),
  ('prod-ref-002', 'main', 'REF-002', 'Pastel Oreo', 'Refrigerados y congelados', 'und', array['und']::text[], array['Pasteles Oreo']::text[], true),
  ('prod-ref-036', 'main', 'REF-036', 'Pepperoni Rebanado', 'Refrigerados y congelados', 'paquete', array['paquete', 'kg']::text[], array['Pepperonis Rebanado']::text[], true),
  ('prod-ref-016', 'main', 'REF-016', 'Queso Azul', 'Refrigerados y congelados', 'und', array['und']::text[], array['Quesos Azul']::text[], true),
  ('prod-ref-025', 'main', 'REF-025', 'Queso Cheese Merchants Parmesan', 'Refrigerados y congelados', 'paquete', array['paquete', 'kg']::text[], array['Quesos Cheese Merchants Parmesan']::text[], true),
  ('prod-ref-015', 'main', 'REF-015', 'Queso Crema Gl', 'Refrigerados y congelados', 'galón', array['galón']::text[], array['Quesos Crema Gl']::text[], true),
  ('prod-ref-039', 'main', 'REF-039', 'Queso Feta', 'Refrigerados y congelados', 'und', array['und']::text[], array['Quesos Feta']::text[], true),
  ('prod-ref-027', 'main', 'REF-027', 'Queso Gouda Block de 2 Kg', 'Refrigerados y congelados', 'bloque', array['bloque', 'kg']::text[], array['Queso Gouda Block de', 'Quesos Gouda Block de']::text[], true),
  ('prod-ref-003', 'main', 'REF-003', 'Queso Mozzarella Rallado Foodie Pizza', 'Refrigerados y congelados', 'paquete', array['paquete']::text[], array['QUESO MOZARELLA RALLADO FOODIE PIZZA', 'Quesos Mozzarella Rallado Foodie Pizza']::text[], true),
  ('prod-ref-044', 'main', 'REF-044', 'Queso mozzarella rebanado', 'Refrigerados y congelados', 'paquete', array['paquete', 'g', 'envase']::text[], array['Queso Mozarella rebanado', 'Quesos mozzarella rebanado', 'mozzarella rebanada', 'Queso Mozzrella Rebanado']::text[], true),
  ('prod-ref-023', 'main', 'REF-023', 'Queso Parmesano Molido (1 Kg) 2,0', 'Refrigerados y congelados', 'paquete', array['paquete', 'g']::text[], array['Queso Parmesano Molido 2,0', 'Quesos Parmesano Molido 2,0']::text[], true),
  ('prod-ref-028', 'main', 'REF-028', 'Queso Provolone', 'Refrigerados y congelados', 'kg', array['kg']::text[], array['QUESO PROVOLONNE', 'Quesos Provolone']::text[], true),
  ('prod-ref-026', 'main', 'REF-026', 'Queso Rebanado Prado Monte Rico , 2.3 Kg Rebanado', 'Refrigerados y congelados', 'bloque', array['bloque', 'kg']::text[], array['Queso Rebanado Prado Monte Rico ,', 'Quesos Rebanado Prado Monte Rico ,']::text[], true),
  ('prod-ref-047', 'main', 'REF-047', 'Queso Turrialba 3 Kg', 'Refrigerados y congelados', 'paquete', array['paquete', 'kg']::text[], array['Queso Turrialba', 'Quesos Turrialba']::text[], true),
  ('prod-ref-037', 'main', 'REF-037', 'Salami Kg', 'Refrigerados y congelados', 'paquete', array['paquete', 'kg']::text[], array['Salami', 'Salamis']::text[], true),
  ('prod-ref-005', 'main', 'REF-005', 'Salchicha Desayuno Kg', 'Refrigerados y congelados', 'kg', array['kg']::text[], array['Salchicha Desayuno', 'Salchichas Desayuno']::text[], true),
  ('prod-ref-021', 'main', 'REF-021', 'Salchichon', 'Refrigerados y congelados', 'kg', array['kg']::text[], array['Salchichones']::text[], true),
  ('prod-ref-040', 'main', 'REF-040', 'Surimi', 'Refrigerados y congelados', 'paquete', array['paquete']::text[], array['SURIME', 'Surimis']::text[], true),
  ('prod-ref-018', 'main', 'REF-018', 'Tacos Hir Pequeños 20 Und (80027)', 'Refrigerados y congelados', 'und', array['und']::text[], array['Tacos Hir Pequeños']::text[], true),
  ('prod-ref-046', 'main', 'REF-046', 'Tartaletas', 'Refrigerados y congelados', 'und', array['und']::text[], array['TARTALETAS MEDIANAS']::text[], true),
  ('prod-ref-007', 'main', 'REF-007', 'Tocineta Americana Caja 6.81kg', 'Refrigerados y congelados', 'caja', array['caja', 'kg']::text[], array['Tocineta Americana', 'Tocinetas Americana']::text[], true),
  ('prod-ref-001', 'main', 'REF-001', 'Tortilla de Trigo Gigante 33 Cm (malinche) Pq 1/10 Ud', 'Refrigerados y congelados', 'paquete', array['paquete']::text[], array['Tortilla de Trigo Gigante', 'Tortillas de Trigo Gigante', 'tortilla malinche', 'tortilla de 33 centímetros']::text[], true),
  ('prod-veg-002', 'main', 'VEG-002', 'Cebolla', 'Vegetales', 'kg', array['kg', 'und', 'bolsa']::text[], array['cebollas']::text[], true),
  ('prod-veg-003', 'main', 'VEG-003', 'Lechuga', 'Vegetales', 'und', array['und', 'kg', 'caja']::text[], array['lechugas']::text[], true),
  ('prod-veg-001', 'main', 'VEG-001', 'Tomate', 'Vegetales', 'caja', array['caja', 'kg', 'und']::text[], array['tomates', 'tomate maduro']::text[], true)
on conflict (id) do update set
  workspace_id = excluded.workspace_id,
  code = excluded.code,
  official_name = excluded.official_name,
  category = excluded.category,
  default_unit = excluded.default_unit,
  allowed_units = excluded.allowed_units,
  synonyms = excluded.synonyms,
  active = excluded.active,
  updated_at = now();
